### ISSUE TITLE
Emit graphite events

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcollective-choria#186]
Make a helper around the current webhook task that emits graphite events as a task

http://graphite.readthedocs.io/en/latest/events.html

```yaml
graphite_event:
  what: "deploy"
  data: "Deployed version {{{ inputs.version }}}"
  graphite: "http://graphite.example.net:8080/events"
  headers:
    "X-Graphite-Token": "foo-foo-foo"
  tags:
    - deploy
    - fooapp
```
