### ISSUE TITLE
Add ability to assert nested hash/array values 

### ISSUE THREAD

**Issue by zipkid** [choria-io/mcollective-choria#192]
Example. To find out if any service failed to restart during a puppet run we need to assert
failed_to_restart, which is not at the top level of the data: hash of last_run_summary.

**Comment by ripienaar** [comment]
the idea here would be to implement a small language similar to what jgrep, jq, pql, etc to do these nested matches.  

Quite a big task and not one I have on my immediate roadmap, i will see if I can think of something meanwhile that gets us closer.

**Comment by vStone** [comment]
Maybe if left/right is an array use a (puppet) dig like function to resolve the result.

**Comment by ripienaar** [comment]
@vStone yeah that's what I intend to do for the short term, longer term we need a whole little grammar with if/and/or/not etc so you can check the combo of things - like puppet for example does not have a single 'idling' concept its the combined state of a few options you have to assert so a grammar is needed

**Comment by ripienaar** [comment]
A reasonable option I have is to embed this stuff http://jsonlogic.com/operations.html 

I know I am not going to be writing a small language myself my patience does not stretch that far so something like this.  Other option is to embed `jq` but that has heavy dependencies

**Comment by ripienaar** [comment]
JSON Logic requires `spec.required_ruby_version = '>= 2.3'`, so this will have to wait till Puppet upgrade to newer, though I am confused why that gem needs that

**Comment by ripienaar** [comment]
Now that Puppet is on new Ruby I had a bit of a look at this:

Scenario: *Is puppet idling or is the daemon absent?*

```
{"or":[{"==":[{"var":"idling"},true]},{"==":[{"var":"daemon_present"},false]}]}
```

or

```yaml
or:
- "==":
  - var: idling
  - true
- "==":
  - var: daemon_present
  - false
```

Scenario: *is `failed_to_restart` true deep in some hash?*

```json
{"==":[{"var":"resources.failed_to_restart"},true]}
```

or

```yaml
"==":
- var: resources.failed_to_restart
- true
```


Idea is we'd embed this in an assert something like:

```yaml
- mcollective_assert:
      description: Wait for Puppet to go idle
      action: puppet.status
      nodes: "{{{ nodes.dev }}}"
      logic:
         or:
         - "==":
           - var: idling
           - true
         - "==":
           - var: daemon_present
           - false
      pre_sleep: 0
      tries: 10
      try_sleep: 30
```

Don't know, what do yous think?  To me this seems rather awful.

We need @ploubser to make jgrep active again which would make everything awesome:

```yaml
- mcollective_assert:
      description: Wait for Puppet to go idle
      action: puppet.status
      nodes: "{{{ nodes.dev }}}"
      logic: "idling = true or daemon_present = false"
      pre_sleep: 0
      tries: 10
      try_sleep: 30
```

**Comment by ploubser** [comment]
@ripienaar jgrep has gained a maintainer and has had a recent release. Anything specific you need?

**Comment by ripienaar** [comment]
@ploubser orly, I missed that, will have a poke :)

**Comment by ripienaar** [comment]
OK @zipkid what do you think if we add assertions to the main `mcollective` task and then drop the god awful `mcollective_assert` task

Using jgrep I now have:

```yaml
  - mcollective:
      description: "Check service restarts"
      action: "puppet.last_run_summary"
      nodes: "{{{ nodes.servers }}}"
      assert: "summary.resources.failed_to_restart=0"
      silent: true
```

or 

```yaml
  - mcollective:
      description: "Wait for enabled Puppet agents to idle"
      action: "puppet.status"
      nodes: "{{{ nodes.servers }}}"
      assert: "applying=false and enabled=true and daemon_present=true"
      silent: true
      tries: 10
      try_sleep: 10
```

This removes the whole need for the `mcollective_assert` and its pretty awesome.  I have one or two thigns to add to JGrep to make it nicer but this will work great I think?
