### ISSUE TITLE
playbook inputs should support saving

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcollective-choria#325]
If an input is statically assigned and has a data store associated it should be able to save that value automatically.

Today this requires:

```yaml
data_stores:
  emulator:
    type: "file"
    file: "~/.choria-emulator.yaml"
    format: "yaml"

inputs:
  emulator_url:
    description: "Emualtor URL (choria-emulator)"
    type: "String"
    validation: ":shellsafe"
    data: "emulator/emulator_url"

hooks:
  pre_book:
    - data:
        action: "write"
        key: "emulator/emulator_url"
        value: "{{{ inputs.emulator_url }}}"
```

But that's ridiculous, this should be possible:

```yaml
data_stores:
  emulator:
    type: "file"
    file: "~/.choria-emulator.yaml"
    format: "yaml"

inputs:
  emulator_url:
    description: "Emualtor URL (choria-emulator)"
    type: "String"
    validation: ":shellsafe"
    data: "emulator/emulator_url"
    save: true # <-- add this and it will auto save the value if statically given
```
