### ISSUE TITLE
Support Puppet Bolt as a playbook task

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcollective-choria#345]
Bolt is a executor for tasks in nodes using commands, tasks or plans and supports windows or winrmi etc https://github.com/puppetlabs/bolt

Create a bolt task type capable of running commands tasks and plans, something like:

```yaml
- bolt
  description: "Run Bolt Task"
  task: "mymodule::mytask"             # or plan or command
  user: "{{{ inputs.user }}}"
  password: "{{{ inputs.password }}}"
  modules: "{{{ inputs.modules }}}"
  nodes: "{{{ nodes.all_nodes }}}"
  transport: ssh
  tty: true
  parameters:
    param1: value
```
