### ISSUE TITLE
mcollective_choria module no longer does deep merge on gem_dependencies in lookup_options

### ISSUE THREAD

**Issue by dnlsng** [choria-io/mcollective-choria#383]
In version 0.4.0 of the mcollective_choria module, we had:
```
lookup_options:
    mcollective_choria::gem_dependencies:
        merge:
            strategy: deep
```
However, it looks like this was missed off when it was split into two modules in 0.5.0.

I'm using mcollective_choria::gem_dependencies in hiera to install the jgrep and diplomat gems. This currently causes the module to not install nats-pure though which is undesirable :).
