### ISSUE TITLE
Problem with a client only installation

### ISSUE THREAD

**Issue by amateo** [choria-io/mcollective-choria#82]
I have tried to install only the client on a node, so I have run:

```
class {'::mcollective':
  client => true,
  server => false,
}
```

Although puppet executions works without any problem, I don't have the _/etc/puppetlabs/mcollective/plugin.d/choria.cfg_ file, so ```mco choria request_cert``` doesn't work.

I have had to manually create this file in order to work.

**Comment by ripienaar** [comment]
Hmm i don't think anything goes in that file. What was the error you had please?

**Comment by amateo** [comment]
```
The choria application failed to run, use -v for full error backtrace details: getaddrinfo: Name or service not known
```

I don't have the DNS configuration, so in that file I should have the hostnames

**Comment by amateo** [comment]
I have those options and they are included in all my _servers_ nodes, but not in the client.

**Comment by ripienaar** [comment]
Ok. To help me reproduce mind sticking your relevant Hiera sections in here? Sounds like a bug then to me

**Comment by amateo** [comment]
This is the configuration I have in hiera applied to all my nodes:
```
mcollective_choria::config:                                                          
  puppetserver_host: "%{hiera('puppet::puppetmaster')}"                              
  puppetca_host: "%{hiera('puppet::ca_server')}"                                     
  puppetdb_host: 'puppetdb.um.es'                                                    
  middleware_hosts:                                                                  
    - 'noctua10.um.es:4222'                                                          
                                                                                     
mcollective::server_config:                                                          
  libdir: '/opt/puppetlabs/mcollective/plugins'                                      
  logger_type: 'syslog'                                                              
  loglevel: 'info'                                                                   
mcollective::plugin_classes:                                                         
  - mcollective_agent_apt                                                            
mcollective::site_policies:                                                          
  - action: 'allow'                                                                  
    callers: 'choria=amateo.mcollective'                                             
    actions: '*'                                                                     
    facts: '*'                                                                       
    classes: '*'                                                                     
  - action: 'allow'                                                                  
    callers: 'choria=amateo_adm.mcollective'                                         
    actions: '*'                                                                     
    facts: '*'                                                                       
    classes: '*'                 
```
